### ISSUE TITLE
cmdCheck kısımlarında

### ISSUE THREAD

**Issue by makbulut1** [makbulut42/ft_irc#3]
User ve nick name ayırt edilir olmalı ve mesajlar nick üzerinden gitmeli.

**Comment by Fartomy** [comment]
Problem cozuldu. Ikisi artik ayri seyler ve sadece username degistiriliebiliyor. Bu arada ayni nickname alinmaya calisildigi zaman client otomatik olarak kendisi nickname atamasi yapiyor.
