### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by Fartomy** [makbulut42/ft_irc#7]
Kodda bir degisilik yapilip (hpp ve cpp dosyalarda) derlenince makefile hata veriyor.

**Comment by makbulut1** [comment]
Nasıl olduğunu tam anlayamadım? Neyden bahsediyorsun?

**Comment by Fartomy** [comment]
Makefile da hpp dosyalarini derlemeye dahil edince aliyordum muhtemelen bu hatayi fakat artik oradan çikardim bağimlilik olarak ekledim muhtemelen problem çözüldü.

**Comment by makbulut1** [comment]
<img width="1053" alt="Ekran Resmi 2023-01-07 ÖS 8 38 01" src="https://user-images.githubusercontent.com/98176777/211163408-edeb6aac-6617-417a-94ba-de72686f40b5.png">

**Comment by makbulut1** [comment]
Furkan böyle bir hata alıyorum
 Clientları array halinde gönder miyor musun? Bunların id'leri yok mu?

**Comment by Fartomy** [comment]
Hocam gönderiyorum çünkü onlara benzer tanımlamaları kullandım

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by makbulut1** [comment]
Fakat neden veriyor o halde bunu anlamadım. Socketfd structının değişkenlerine de ulaşamıyorum. Neyse yemek yiyip bakacağım

**Comment by Fartomy** [comment]
Bakarız hocam

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Fartomy** [comment]
Hocam client'lari vector array'in de tutuyorum, id'leri de bizim commandChecker da olmasi lazim

**Comment by makbulut1** [comment]
Tamamdir hallettim Proje tamamlanmak üzere :)
